spring:
  datasource:
    url: jdbc:postgresql://stepan-ovsyannikov-db.c6zsa0ei03bh.us-east-1.rds.amazonaws.com:5432/postgres?ssl=true&sslmode=require
    username: iam_database_user
    password:
    driver-class-name: org.postgresql.Driver
    hikari:
      max-lifetime: 840000

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    loggers: slf4j
    clean-disabled: false

aws:
  s3:
    bucket-name: stepan-ovsyannikov-bucket1
    region: us-east-1
    folder: rds/

local:
  filePath: downloads

logging:
  level:
    org.flywaydb: DEBUG
    org.springframework.jdbc: DEBUG